### ISSUE TITLE
production checklist

### ISSUE THREAD

**Issue by zeke** [electron/update.electronjs.org#33]
Nice things to have done before we make an announcement:

- [x] make the repo public
- [x] #15 
- [x] #30 
- [ ] ~bump dyno count to two~
- [x] set up slack notifications for 400s and 500s
- [x] https://github.com/electron/update-electron-app/pull/6
